// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Skill{
    id:          number;
    characterId: number;
    name:        string;
    rank:        string;
    description: string;
}
